formklcass/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path

from . import views


urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('new/', views.post_new, name='post_new'),
    path('<int:pk>/edit/', views.post_edit, name='post_edit'),
    path('<int:pk>/detail/', views.post_detail, name='post_detail'),
    path('<int:post_pk>/comment/new', views.comment_new, name='comment_new'),
    path('<int:post_pk>/comment/<int:pk>/edit', views.comment_edit, name='comment_edit'),
]

accounts/models.py
from django.conf import settings
from django.core.validators import RegexValidator
from django.db import models


class Profile(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=11, validators=[RegexValidator(r'^010[1-9]\d{7}$')])

myapp/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.shortcuts import reverse


class Post(models.Model):
    title = models.CharField(max_length=100, validators=[MinLengthValidator(3)])
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
        return reverse("post_detail", args=[self.pk])

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    author = models.CharField(max_length=20)
    message = models.TextField()
    ip = models.CharField(max_length=15)

    def __str__(self):
        return "{}: {}".format(self.author, self.message)

class GameUser(models.Model):
    server = models.CharField(max_length=10)
    username = models.CharField(max_length=20, validators=[MinLengthValidator(3)])

    class Meata:
        unique_together = [
            ('server', 'username'),
        ]

myapp/forms.py
from django import forms

from .models import Post, Comment, GameUser


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = '__all__'


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['author', 'message']


class GameUserSignupForm(forms.ModelForm):
    class Meta:
        model = GameUser
        fields = ['server', 'username']
    
    def clean_username(self):
        '''
        값 변환은 clean 함수에서만 가능합니다.
        validator에서는 지원하지 않습니다.
        '''
        return self.cleaned_data.get('username','').strip()

accounts/views.py
from django.shortcuts import render

# Create your views here.

myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import PostForm, CommentForm
from .models import Post, Comment

def post_list(request):
    post_list = Post.objects.all()
    return render(request, 'myapp/post_list.html', {
        'post_list': post_list
    })

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'myapp/post_detail.html', {
        'post': post
    })

def post_new(request):
    form_cls = PostForm
    template_name = 'myapp/post_form.html'
    success_url = '/'

    if request.method == 'POST':
        form = form_cls(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            return redirect(post)
    else:
        form = form_cls()

    return render(request, template_name, {
        'form': form,
    })


def post_edit(request, pk):
    form_cls = PostForm
    template_name = 'myapp/post_form.html'
    success_url = '/'

    post = get_object_or_404(Post, pk=pk)

    if request.method == 'POST':
        form = form_cls(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            return redirect(success_url)
    else:
        form = form_cls(instance=post)

    return render(request, template_name, {
        'form': form,
    })


def comment_new(request, post_pk):
    form_cls = CommentForm
    template_name = 'myapp/comment_form.html'
    success_url = '/'

    post = get_object_or_404(Post, pk=post_pk)

    if request.method == 'POST':
        form = form_cls(request.POST, request.FILES)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.ip = request.META['REMOTE_ADDR']
            comment.save()
            return redirect(success_url)
    else:
        form = form_cls()

    return render(request, template_name, {
        'form': form,
    })


def comment_edit(request, post_pk, pk):
    form_cls = CommentForm
    template_name = 'myapp/comment_form.html'
    success_url = '/'

    comment = get_object_or_404(Comment, pk=pk)

    if request.method == 'POST':
        form = form_cls(request.POST, request.FILES, instance=comment)
        if form.is_valid():
            comment = form.save()
            return redirect('/')
    else:
        form = form_cls(instance=comment)

    return render(request, template_name, {
        'form': form,
    })

myapp/templates/myapp/comment_form.html
<h1>Comment Form</h1>

<form action="" method='post'>
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="저장">
</form>

myapp/templates/myapp/post_detail.html
<h2>{{ post.title }}</h2>

{{ post.content|safe }}

<hr>

<ul>
    {% for comment in post.comment_set.all %}
        <li>
            {{ comment.message }} by
            {{ comment.author }}
            <small>{{ comment.ip }}</small>
            <a href="{% url 'comment_edit' post.pk comment.pk %}">수정</a>
        </li>
    {% endfor %}
</ul>

<hr>
<a href="{% url 'post_list' %}">목록으로 가기</a>
<a href="{% url 'comment_new' post.pk %}">댓글 쓰기</a>

myapp/templates/myapp/post_form.html
<!DOCTYPE html>
<html lang="ko">
    <head>
        <title></title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- include libraries(jQuery, bootstrap) -->
<link href="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script> 
<script src="http://netdna.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.js"></script> 

<!-- include summernote css/js -->
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">
<script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js"></script>
    </head>
    <body>
        <h1>Post Form</h1>

        <form action="" method='post'>
            {% csrf_token %}
            <table>
                {{ form.as_table }}
            </table>
            <input type="submit" value="저장">
        </form>

        <script>
            $(document).ready(function() {
                $('#id_content').summernote();
            });
        </script>
    </body>
</html>

myapp/templates/myapp/post_list.html
<table>
    <tbody>
        {% for post in post_list %}
            <tr>
                <td>{{ post.pk }}</td>
                <td>
                    <a href="{% url 'post_detail' post.pk %}">
                        {{ post.title }}
                    </a>
                </td>
                <td>{{ post.content|safe }}</td>
                <td>
                    <a href="{% url 'post_edit' post.pk %}">수정</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>